trigger:
- main

pool:
  name: devpool

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: Maven@4
  displayName: Compile
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: Maven@4
  displayName: Build
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
  
- task: Docker@2
  displayName: Docker Build
  inputs:
    containerRegistry: 'docker-conn'
    repository: 'brd'
    command: 'build'
    Dockerfile: '**/Dockerfile'

- task: Docker@2
  displayName: Docker Push
  inputs:
    containerRegistry: 'docker-conn'
    repository: 'brd'
    command: 'push'

  